### ISSUE TITLE
Support for Page on Top & Below

### ISSUE THREAD

**Issue by otymartin** [msaps/Pageboy#18]
@msaps 
Is there any plan to support pages on top or below?
Im looking to create a 3 page view [Left, Center, Top] where Top is above Left.

Also side question didnt want to raise issue but can bounce be disabled on First and Last page?

**Comment by msaps** [comment]
Hi, 

As `Pageboy` is just a wrapper around `UIPageViewController` that sort of layout isn't really possible. The `navigationOrientation` can be changed to achieve either horizontal/vertical page layout but unfortunately not a hybrid of the two.

You could probably achieve this sort of layout using a horizontal `Pageboy` and a scroll view / gesture recognizer combination to get the top view controller?

I'll raise a separate issue and get a `bounces` property added in the next release. :+1:

**Comment by otymartin** [comment]
@msaps Thanks
Just a one more question on the layout i want `[Left, Center, Top]`
What I technically want do is 3 pages [left, center, top], but User can only swipe between left and center. Going to the top I'd rather use a button to present the top view. Reason being I want a camera view in that `top` page so that its already loaded. Currently I hate that I have to stare at a black screen for 3-5 seconds before my cameraViewController previewlayer loads.

Can I do that? Present a `page` without the swipe/transition animation? and prevent swipe to either first page, last page or both?

**Comment by msaps** [comment]
@otymartin You could achieve that hierarchy with something like this..

**Comment by msaps** [comment]
@otymartin you could achieve that view hierarchy with something like this:

```
ParentViewController
     -> UIScrollView
          -> TopViewController
          -> PageboyViewController
               -> LeftViewController
               -> CenterViewController
```
You could then switch between the (Left/Center) pages and the top view controller by having a button which adjusts the scroll view's `contentOffset` to the required state value. Just have the `UIScrollView` with `scrollEnabled` set to `false`.

**Comment by msaps** [comment]
@otymartin a `bounces` property is now available in `PageboyViewController` as of 0.4.11 😄

**Comment by otymartin** [comment]
@msaps 
Hey thanks for the detailed responses with suggestions. I'll be implementing this library tomorrow and thanks for adding the bounces property. althougth the more I try the example, i'm attracted to the interpolating background color effect your have where it darkens as you try to scroll beyond the bounds of the scroll view.
very nice!

**Comment by msaps** [comment]
@otymartin no worries! The gradient interpolation code is in found in the following functions:

```swift 
func updateAppearance(pageOffset: CGFloat) 

func gradient(forIndex index: Int) -> GradientConfig

func interpolate(betweenColor colorA: UIColor,
                 and colorB: UIColor,
                 percent: CGFloat) -> UIColor?
```
 in `PageViewControllerAppearance.swift`.

**Comment by otymartin** [comment]
@msaps very nice, I love how they blend in so nicely its just awesome. Makes the infinite scroll more seamless
