### ISSUE TITLE
Embedding UITableView in Pageboy

### ISSUE THREAD

**Issue by joeljfischer** [msaps/Pageboy#23]
When I'm embedding a UITableView in a child view controller, I am unable to get vertical scrolling to work. Is there some API that I'm missing here? Should I be causing the underlying pan gesture recognizers to interact in some way?

**Comment by msaps** [comment]
Hi @joeljfischer, did you get the source of this problem?

**Comment by joeljfischer** [comment]
Yep, my fault. It all works as expected. Thanks!
